name: advent-of-code
version: 0.1.0.0
github: "raphaelmeyer/advent-of-code-2021"
license: MIT

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -Wall
  - -Werror
  - -O2

library:
  source-dirs: src
  dependencies:
    - text
    - megaparsec
    - containers

executables:
  day-01-exe:
    main: Main.hs
    source-dirs: app/Day01
    dependencies:
      - advent-of-code

  day-03-exe:
    main: Main.hs
    source-dirs: app/Day03
    dependencies:
      - advent-of-code

  day-05-exe:
    main: Main.hs
    source-dirs: app/Day05
    dependencies:
      - advent-of-code

  day-06-exe:
    main: Main.hs
    source-dirs: app/Day06
    dependencies:
      - advent-of-code

  day-07-exe:
    main: Main.hs
    source-dirs: app/Day07
    dependencies:
      - advent-of-code

  day-09-exe:
    main: Main.hs
    source-dirs: app/Day09
    dependencies:
      - advent-of-code

  day-10-exe:
    main: Main.hs
    source-dirs: app/Day10
    dependencies:
      - advent-of-code

  day-12-exe:
    main: Main.hs
    source-dirs: app/Day12
    dependencies:
      - advent-of-code


tests:
  test:
    main: Spec.hs
    source-dirs: test
    when:
      - condition: false
        other-modules: Paths_advent_of_code
    dependencies:
      - advent-of-code
      - hspec
      - hspec-discover
      - text
      - containers
